### ISSUE TITLE
File Cleaning Error

### ISSUE THREAD

**Issue by OrhunKok** [WEHI-Proteomics/tfde#1]
Hello, I am trying do a simple run of your package using one experiment but I get a file removal error.

Here is my bulk-run.sh:

```
#!/bin/bash
set -e

python -m doit -f ./tfde/pipeline/execute-run.py clean en=JD1527 eb="/home/kok.o"
python -m doit -f ./tfde/pipeline/execute-run.py pc=0.8 cs=true fmdw=true en=JD1527 rn=JD1527_rep_1_GE5_1_1107.d,JD1527_rep_2_GE5_1_1108.d,JD1527_rep_3_GE5_1_1109.d,JD1527_rep_4_GE5_1_1110.d,JD1527_rep_5_GE5_1_1111.d rl=0 ru=3000 ff="/home/kok.o/fasta/swissprot_HYE_CanIso_02142022.fasta" ini='/home/kok.o/tfde/pipeline/pasef-process-short-gradient.ini' eb="/home/kok.o"
```

Here is the error I get:

```
TaskFailed
Command failed: 'rm /home/kok.o/JD1527/target-decoy-models/target-decoy-classifier.pkl' returned 1
TaskFailed
Command failed: 'rm /home/kok.o/JD1527/target-decoy-models/experiment-metrics-for-library-sequences.sqlite' returned 1
```

It seems the execute-run.py fails to clean up a temporary file it makes, and this causes the script to break. Do you know what could be causing this?

**Comment by OrhunKok** [comment]
I had to remove the .d extension from the replicate files in the script to fix that error

**Comment by DarylWM** [comment]
Hi. Thanks for trying out our software. Yes the `rn` argument is for specifying the run name, not the run's database name.
